[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
colored = "2.1.0"
itertools = "0.13.0"
num-rational = "0.4.2"
priority-queue = "2.1.1"
rand = "0.8.5"
regex = "1.11.1"
